apiVersion: workflow/v1
kind: WorkflowTemplate
metadata:
  name: fetch-etcd
  description: Fetch a value from etcd at a given path

spec:
  arguments:
    parameters:
      etcd_server: ""
      etcd_path: ""

  steps:
    - name: fetch-value
      action: etcd.fetch
      plugin_version: v1.0.2
      with:
        etcd_server: "{{ inputs.etcd_server }}"
        etcd_path: "{{ inputs.etcd_path }}"
